# Araay Basics

In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
# Create a 1D_array size 4:
x1D = [None]*4
for i in range(len(x1D)):
  x1D[i] = input("Enter sane type of data :")
print(f'1D Array is : {x1D}')

Enter sane type of data :Mahin
Enter sane type of data :Lost
Enter sane type of data :Jahid
Enter sane type of data :Noor
1D Array is : ['Mahin', 'Lost', 'Jahid', 'Noor']


In [ ]:
# Create a 2D_array size (2,3):
x2D = [None]*2
for i in range(len(x2D)):
  x2D[i] = [None] * 3
print(f'2D Array is : {x2D}')

2D Array is : [[None, None, None], [None, None, None]]


In [ ]:
# Create a 3D_array size (2,3,4):
x3D = [None]*2
for i in range(len(x3D)):
  x3D[i] = [None] * 3
  for j in range(len(x3D[i])):
    x3D[i][j] = [None] * 4
print(f'3D Array is : {x3D}')

3D Array is : [[[None, None, None, None], [None, None, None, None], [None, None, None, None]], [[None, None, None, None], [None, None, None, None], [None, None, None, None]]]


In [ ]:
# How enter a list in array :
x = [None] * 10
l = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

for i in range(10):
  x[i] = l[i]
print(x)

print(x[4]) # access by index

# change a value / element by index :
x[4] = "LOST"
print(x[4])

['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']
Ifty
LOST


In [ ]:
# Iteration :
def iteration(source):
  for i in range(len(source)):
    print(source[i])

def reverseIteration (source):
  for i in range(len(source) -1, -1, -1):
    print(source[i])

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

iteration(array)
print()
reverseIteration(array)

Emon
Nusrat
Joy
Abrar
Ifty
Ashik
Raisa
Suba
Sazid
Jawad

Jawad
Sazid
Suba
Raisa
Ashik
Ifty
Abrar
Joy
Nusrat
Emon


In [ ]:
# Copy aay :
def copyarray(a):
  newaay = [None] * len(a)
  for i in range(len(a)):
    newaay[i] = a[i]
  return newaay

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

print(copyarray(array))

['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']


In [ ]:
# Resize aay :
def resizearray (oldarray, newCapacity):
  newarray = [None] * newCapacity
  for i in range(len(oldarray)):
    newarray[i] = oldarray[i]
  return newarray

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

a = resizearray(array, 16)
print(a)

['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad', None, None, None, None, None, None]


In [ ]:
# Reversing an aay:
def reversearrayOutOfPlace (a):
  reva = [None] * len(a)
  i = 0
  j = len(a) - 1
  while i < len(a):
    reva[i] = a[j]
    i += 1
    j -= 1
  return reva

def revaInPlace (a):
  i = 0
  j = len(a) - 1
  while i<j:
    temp = a[i]
    a[i] = a[j]
    a[j] = temp
    i += 1
    j -= 1
  return a

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

a = reversearrayOutOfPlace(array)
print(a)
print()
b = revaInPlace(array)
print(b)

['Jawad', 'Sazid', 'Suba', 'Raisa', 'Ashik', 'Ifty', 'Abrar', 'Joy', 'Nusrat', 'Emon']

['Jawad', 'Sazid', 'Suba', 'Raisa', 'Ashik', 'Ifty', 'Abrar', 'Joy', 'Nusrat', 'Emon']


In [ ]:
# Shifting left :
def shiftLeft(a):
  for i in range(1, len (a)):
    a[i-1] = a[i]
  a[len(a) - 1] = None
  return a

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

a = shiftLeft(array)
print(a)

['Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad', None]


In [ ]:
# Shifting right :
def shiftRight (a):
  for i in range(len(a) - 1, 0, -1):
    a[i] = a[i - 1]
  a[0]= None
  return a

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

b = shiftRight(array)
print(b)

[None, 'Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid']


In [ ]:
# Rotate lrft :
def rotateLeft(a):
  temp = a[0]
  for i in range(1, len(a)):
    a[i-1] = a[i]
  a[len(a) - 1] = temp
  return a

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

a = rotateLeft(array)
print(a)

['Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad', 'Emon']


In [ ]:
# Rotate Right :
def rotateRight(arr):
  temp = arr[len (arr) - 1]
  for i in range(len(arr) - 1, 0, -1):
    arr[i] = arr[i - 1]
  arr[0] = temp
  return arr

array = ['Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid', 'Jawad']

a = rotateRight(array)
print(a)

['Jawad', 'Emon', 'Nusrat', 'Joy', 'Abrar', 'Ifty', 'Ashik', 'Raisa', 'Suba', 'Sazid']


In [ ]:
# Insert Element in array :
def insertElement (arr, size, e, i): # Here array size shows how many elements are in array
  if size == len(arr):
    print("No space left. Insertion failed")
  else:
    for i in range(size, i, -1):
      arr[i] = arr[i - 1]
    arr[i] = e
    return arr

a = [None]*4
a[0] = "Noor"
a[1] = "Nahar"
print(a)
x = insertElement(a, 2, "Mahin", 2)
print(x)

['Noor', 'Nahar', None, None]
['Noor', 'Nahar', 'Mahin', None]


In [ ]:
# Removing a element :
# def removeElement(arr, index, size):
#   for i in range(index + 1, size):
#     arr[i - 1] = arr[i]              #Shifting left from removing index
#   arr[size - 1] = None               #Making last space empty
#   return arr

def removeElement(arr, index, size):
  for i in range(size):
    if i == index:
      arr[i] = None
  return arr

a = [None]*4
a[0] = "Noor"
a[1] = "Nahar"
print(a)

x = removeElement(a, 1, 4)
print(x)

['Noor', 'Nahar', None, None]
['Noor', None, None, None]


# Multidimensional Array

In [ ]:
# use of numpy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
array0 = np.zeros(5)
print(array0)
array1 = np.ones(4)
print(array1)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.zeros((2,3))
print(arr)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [ ]:
arr = np.zeros((2,3,5)) #****  understand how it works
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
# To access multi demention array
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    arr[i][j] = 4
print(arr)

[[[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]


In [ ]:
array_3D = np.zeros((4,5,6))

for i in range(array_3D.shape[0]):
  for j in range(array_3D.shape[1]):
    for k in range(array_3D.shape[2]):
      array_3D[i][j][k] = i*100+j*10+k

print(array_3D)

[[[  0.   1.   2.   3.   4.   5.]
  [ 10.  11.  12.  13.  14.  15.]
  [ 20.  21.  22.  23.  24.  25.]
  [ 30.  31.  32.  33.  34.  35.]
  [ 40.  41.  42.  43.  44.  45.]]

 [[100. 101. 102. 103. 104. 105.]
  [110. 111. 112. 113. 114. 115.]
  [120. 121. 122. 123. 124. 125.]
  [130. 131. 132. 133. 134. 135.]
  [140. 141. 142. 143. 144. 145.]]

 [[200. 201. 202. 203. 204. 205.]
  [210. 211. 212. 213. 214. 215.]
  [220. 221. 222. 223. 224. 225.]
  [230. 231. 232. 233. 234. 235.]
  [240. 241. 242. 243. 244. 245.]]

 [[300. 301. 302. 303. 304. 305.]
  [310. 311. 312. 313. 314. 315.]
  [320. 321. 322. 323. 324. 325.]
  [330. 331. 332. 333. 334. 335.]
  [340. 341. 342. 343. 344. 345.]]]


In [ ]:
def matrix_multiplication(array_1,array_2):
  if array_1.shape[1]!=array_2.shape[0]:
    print("Matrix multiplication not possible, wrong dimensions")
    return

  m = array_1.shape[0]
  n = array_1.shape[1]
  p = array_2.shape[1]

  result = np.zeros((m,p), dtype = int)

  for i in range(m):
    for j in range(p):
      sum=0
      for k in range(n):
        sum += array_1[i][k]*array_2[k][j]
      result[i][j] = sum
  return result

array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[7,8],[9,10],[11,12]])

print(matrix_multiplication(array_1,array_2))

[[ 58  64]
 [139 154]]


In [ ]:
# Convert a list into an array
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


# Linked List

In [ ]:
# Linked List Creation
#**** Node class design****
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n  # Adress of the next element.


# Linked List Creation from an Array
def createList(a):
  head = Node(a[0], None)
  tail = head
  for i in range (1, len(a)):
    n = Node(a[i], None)
    tail.next = n
    tail = tail.next
  return head  # This line will return the location of Head.


# Iterating Over a Linked List
def iteration (head):
    temp = head
    while temp != None:
      print(temp.elem)
      temp = temp.next


# Counting elements of a Linked List
def count (head):
  count = 0
  temp = head
  while temp != None:
    count += 1
    temp = temp.next
  return count


# Retrieving an element from an index** Getting ekement of an specific index
def elemAt (head, idx):
  count = 0
  temp = head
  obj = None
  while temp != None:
    if count == idx:
      obj = temp.elem
      break
    temp = temp.next
    count += 1
  if obj == None:
     print("Invalid index")
  return obj


# Retrieving a node from an index **Getting a node from an index
def nodeAt (head, idx):
  count = 0
  temp = head
  obj = None
  while temp != None:
    if count == idx:
      obj = temp
      break
    temp = temp.next
    count += 1
  if obj == None:
    print("Invalid index")
  return obj



#Update value of specific index
def set (head, idx, elem):
  count = 0
  temp = head
  isUpdated = False
  while temp != None:
    if count == idx:
      temp.elem = elem
      isUpdated = True
      break
    temp = temp.next
    count += 1
  if isUpdated:
    print("Value successfully updated!!!!")
  else:
    print("Invalid index")


# Searching an element in the list
def contains (head, elem):
  temp = head
  while temp != None:
    if elem == temp.elem:
      return True
    temp == temp.next
  return False


# Searching an element in the list with index
def indexOf(head, elem):
  temp = head
  count = 0
  while temp != None:
    if elem == temp.elem:
      return count
    count += 1
    temp = temp.next
  return -1 # Here -1 represents the absence of element in the list


# Inserting an element into a list
def insert (head, elem, idx):
  total_nodes = count (head)
  if idx == 0: # Inserting at the beginning
    n = Node(elem, head)
    head = n
  elif idx >= 1 and idx < total_nodes: # Inserting at the middle
    n = Node(elem, None)
    n1 = nodeAt (head, idx = 1)
    n2 = nodeAt (head, idx)
    n.next = n2
    n1.next= n
  elif idx == total_nodes: # Inserting at the end
    n = Node(elem, None)
    n1 = nodeAt (head, total_nodes - 1)
    n1.next = n
  else:
    print("Invalid Index")
  return head


# Removing an element from a list
def remove (head, idx):
  if idx == 0: # Removing first element
    head = head.next
  elif idx >= 1 and idx < count (head): # Remov
    n1 = nodeAt(head, idx - 1)
    removed_node = n1.next
    n1.next = removed_node.next
  else:
    print("Invalid Index")
  return head


# Copying a list
def copyList(source):
  copy_head = None
  copy_tail = None
  temp = source
  while temp != None:
    n = Node(temp.elem, None)
    if copy_head == None:
      copy_head = n
      copy_tail = copy_head
    else:
      copy_tail.next = n
      copy_tail = copy_tail.next
    temp = temp.next
  return copy_head


# Reversing a list - out of place
def reverse_out_of_place (head):
  new_head = Node(head.elem, None)
  temp = head.next
  while temp != None:
    n = Node(temp.elem, new_head)
    new_head = n
    temp = temp.next
  return new_head


# Reversing a list - in place
def reverse_in_place(head):
  new_head = None
  temp = head
  while temp != None:
    n = temp.next
    temp.next = new_head
    new_head = temp
    temp = n
  return new_head


# Rotating a list - left
def rotate_left(head):
  new_head = head.next
  temp = new_head
  while temp.next != None:
    temp = temp.next
  temp.next = head
  head.next = None
  head = new_head
  return head


# Rotating a list - right
def rotate_right (head):
  last_node = head.next
  second_last_node = head
  while last_node.next != None:
    last_node = last_node.next
    second_last_node = second_last_node.next
  last_node.next = head
  second_last_node.next = None
  head = last_node
  return head

# Quiz **1**

In [ ]:
# Quiz 1 Question 1 Okay Done
def removeElement(LinArr,size,idx):
  for i in range(len(LinArr)):
    if i == idx:
      LinArr[i] = None
  for i in range(idx + 1,len(LinArr)):
    LinArr[i - 1] = LinArr[i]
  return LinArr

print(removeElement([7,12,1,2,3,5,None], 6, 1 ))
print(removeElement([1,3,75,35,30,4, None], 7, 4))

[7, 1, 2, 3, 5, None, None]
[1, 3, 75, 35, 4, None, None]


In [ ]:
# Quiz 1 Question 2  ********* Didn't use Node class or linked list, why ???????
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

def increase( list ):
  for i in range(len(list)):
    list[i] = list[i] + 1
  return list

list = [2,6,4,8]
print(increase(list))

[3, 7, 5, 9]


# 22299543_Multi_Dim_Evaluation.ipynb

In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

In [ ]:
# Advance
import numpy as np
def flip_vertical(matrix):
  rows, columns = matrix.shape
  new_array = matrix[::-1, :]        #****Iteration****#
  return new_array

#Driver Code
#DO NOT CHANGE ANYTHING BELOW
print("=======TEST 1=======")
m = np.random.randint(15,size=(4,4)) #This creates an np array of 4 x 3 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))
print()

print("=========TEST 2=========")
m = np.random.randint(15,size=(5,5)) #This creates an np array of 5 x 4 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))

=======TEST 1=======
|  13 |  10 |  11 |  2  |
-------------------------
|  4  |  11 |  12 |  2  |
-------------------------
|  2  |  5  |  9  |  11 |
-------------------------
|  2  |  6  |  8  |  4  |
-------------------------

|  2  |  6  |  8  |  4  |
-------------------------
|  2  |  5  |  9  |  11 |
-------------------------
|  4  |  11 |  12 |  2  |
-------------------------
|  13 |  10 |  11 |  2  |
-------------------------

=========TEST 2=========
|  2  |  7  |  11 |  12 |  11 |
-------------------------------
|  12 |  0  |  2  |  11 |  14 |
-------------------------------
|  13 |  1  |  4  |  9  |  6  |
-------------------------------
|  0  |  10 |  0  |  1  |  5  |
-------------------------------
|  9  |  3  |  2  |  9  |  5  |
-------------------------------

|  9  |  3  |  2  |  9  |  5  |
-------------------------------
|  0  |  10 |  0  |  1  |  5  |
-------------------------------
|  13 |  1  |  4  |  9  |  6  |
-------------------------------
|  12 |  0  |  2  |  11

In [ ]:
# Problem Solved by me:
def flip_vertically(matrix):
  rows, columns = matrix.shape
  new_array = np.zeros((rows, columns))
  for row in range(rows):
    for column in range(columns - 1, -1, -1):
      new_array[row][column] = matrix[row][column]
  return new_array

#Driver Code
#DO NOT CHANGE ANYTHING BELOW
print("=======TEST 1=======")
m = np.random.randint(15,size=(4,4)) #This creates an np array of 4 x 3 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))
print()

print("=========TEST 2=========")
m = np.random.randint(15,size=(5,5)) #This creates an np array of 5 x 4 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))

=======TEST 1=======
|  9  |  4  |  2  |  0  |
-------------------------
|  1  |  14 |  9  |  13 |
-------------------------
|  0  |  13 |  5  |  11 |
-------------------------
|  13 |  4  |  4  |  14 |
-------------------------

|  13 |  4  |  4  |  14 |
-------------------------
|  0  |  13 |  5  |  11 |
-------------------------
|  1  |  14 |  9  |  13 |
-------------------------
|  9  |  4  |  2  |  0  |
-------------------------

=========TEST 2=========
|  9  |  8  |  5  |  7  |  7  |
-------------------------------
|  10 |  14 |  2  |  11 |  8  |
-------------------------------
|  4  |  9  |  8  |  2  |  5  |
-------------------------------
|  6  |  9  |  0  |  13 |  11 |
-------------------------------
|  6  |  3  |  5  |  2  |  11 |
-------------------------------

|  6  |  3  |  5  |  2  |  11 |
-------------------------------
|  6  |  9  |  0  |  13 |  11 |
-------------------------------
|  4  |  9  |  8  |  2  |  5  |
-------------------------------
|  10 |  14 |  2  |  11

In [ ]:
# Flip upside down:
def flip_vertically(array):
  new_array = []
  for i in range(len(array)-1, -1, -1):
    new_row = []
    for j in range(len(array[0])):
      new_row.append(array[i][j])
    new_array.append(new_row)
    arr = np.array(new_array)
  return arr

array = [[8, 10, 2], [3, 14, 14], [0, 4, 7], [10, 10, 0]]
new_array = flip_vertically(array)
print(new_array)

[[10 10  0]
 [ 0  4  7]
 [ 3 14 14]
 [ 8 10  2]]


In [ ]:
# Flip by side:
def flip_array(array):
  new_array = []
  for row in array:
    new_row = row[::-1]
    new_array.append(new_row)
  return new_array
if __name__ == "__main__":
  # Create a 2D array.
  array = [[8, 10, 2], [3, 14, 14], [0, 4, 7], [10, 10, 0]]

  # Flip the array vertically.
  new_array = flip_array(array)

  # Print the new array.
  for row in new_array:
    print(row)

[2, 10, 8]
[14, 14, 3]
[7, 4, 0]
[0, 10, 10]


# Extra Task of Lab 3

In [ ]:
class Node:
  def __init__(self,elem,next = None):
    self.elem, self.next = elem,next

In [ ]:
class LinkedList:
  def __init__(self,arr):
    self.head = Node(arr[0])
    tail = self.head
    for i in range(1,len(arr)):
      newNode = Node(arr[i])
      tail.next = newNode
      tail = newNode

  def printLinkedList(self):
    temp = self.head
    while temp != None:
      if temp.next != None:
        print(temp.elem, end = '-->')
      else:
        print(temp.elem)
      temp = temp.next

  def countNodes(self):
    count = 0
    temp = self.head
    while temp != None:
      count += 1
      temp = temp.next
    return count

  def nodeAt(self, idx):
    count = 0
    temp = self.head
    obj = None
    while temp != None:
      if count == idx:
        obj = temp
        break
      temp = temp.next
      count += 1
    if obj == None:
      print("Invalid index")
    return obj


  def elemAt(self,idx):
    count = 0
    temp = self.head
    obj = None
    while temp != None:
      if count == idx:
        obj = temp. elem
        break
      temp = temp.next
      count += 1
    if obj == None:
      print("Invalid index")
    return obj

  def indexOf(self,value):
    temp = self.head
    count = 0
    while temp != None:
      if value == temp.elem:
        return count
      count += 1
      temp = temp.next
    return "Unknown"

  def contains(self, value):
    temp = self.head
    flag = False
    while temp != None:
      if value == temp.elem:
        flag = True
        return flag
      temp = temp.next
    return flag

  def insert(self, value, idx): #Done for students
    newNode = Node(value)
    if idx == 0:
      newNode.next = self.head
      self.head = newNode
    else:
      prev = self.nodeAt(idx-1)
      if prev != None:
        newNode.next = prev.next
        prev.next = newNode

  def remove(self, idx):
    if idx == 0:
      self.head = self.head.next
    elif idx >= 1 and idx < self.countNodes():
      n1 = self.nodeAt(idx - 1)
      removed_node = n1.next
      n1.next = removed_node.next
    else:
      print("Invalid Index")

  def rotateRight(self):                  # -2 Was vanished from output. Why????
    last_node = self.head.next
    second_last_node = self.head
    while last_node.next != None:
      last_node = last_node.next
      second_last_node = second_last_node.next
    last_node.next = self.head
    second_last_node.next = None
    head = last_node
    return head

  def rotateLeft(self):
    new_head = self.head.next
    temp = new_head
    while temp.next != None:
      temp = temp.next
    temp.next = self.head
    self.head.next = None
    self.head = new_head  # Update the head attribute
    return self.head

print('Create Linked List')
l1 = LinkedList(np.array([10,34,21,6,-2]))
l1.printLinkedList()
print()

print('Count Nodes of Linked List')
print(l1.countNodes())
print()

print('Find out the node at a certain index')
n = l1.nodeAt(3)
print('Node at index 3:', end = ' ')
print(n.elem if n!=None else 'Invalid Index')
print('Corner Cases:')
print('Node at index -1:', end = ' ')
n = l1.nodeAt(-1)
print(n.elem if n!=None else 'Invalid Index')
print('Node at index 5:', end = ' ')
n = l1.nodeAt(5)
print(n.elem if n!=None else 'Invalid Index')
print()

print('Find out the element at a certain index')
print('Element at index 1:', end = ' ')
print(l1.elemAt(1))
print('Corner Cases:')
print('Element at index -2:', end = ' ')
print(l1.elemAt(-2))
print('Element at index 6:', end = ' ')
print(l1.elemAt(6))
print()

print('Find out the index of an element')
print('Index of element -2 is', end = ' ')
print(l1.indexOf(-2))
print('Corner Cases:')
print('Index of element 23 is', end = ' ')
print(l1.indexOf(23))
print()

print('Find out the if linked list contains an element')
print('Linked List contains -2:', end = ' ')
print(l1.contains(-2))
print('Corner Cases:')
print('Linked List contains 3:', end = ' ')
print(l1.contains(3))
print()

print('Insert element in certain index')
print('Insert 41 at index 2:', end = ' ')
l1.insert(41,2)
l1.printLinkedList()
print('Corner Cases:')
print('Insert 25 at index 0:', end = ' ')
l1.insert(25,0)
l1.printLinkedList()
print('Insert 15 at index 7:', end = ' ')
l1.insert(15,7)
l1.printLinkedList()
print('Insert 27 at index -1:', end = ' ')
l1.insert(27,-1)
l1.printLinkedList()
print()

print('Delete node from a certain index')
print('Delete from index 5:', end = ' ')
l1.remove(5)
l1.printLinkedList()
print('Corner Cases:')
print('Delete from index 0:', end = ' ')
l1.remove(0)
l1.printLinkedList()
print('Delete from index 5:', end = ' ')
l1.remove(5)
l1.printLinkedList()
print('Delete from index -1:', end = ' ')
l1.remove(-1)
l1.printLinkedList()
print()

print('Right Rotate')
l1.printLinkedList()
print()
l1.rotateRight()
l1.printLinkedList()
print()

print('Left Rotate')
l1.printLinkedList()
print()
l1.rotateLeft()
l1.printLinkedList()
print()

Create Linked List
10-->34-->21-->6-->-2

Count Nodes of Linked List
5

Find out the node at a certain index
Node at index 3: 6
Corner Cases:
Node at index -1: Invalid index
Invalid Index
Node at index 5: Invalid index
Invalid Index

Find out the element at a certain index
Element at index 1: 34
Corner Cases:
Element at index -2: Invalid index
None
Element at index 6: Invalid index
None

Find out the index of an element
Index of element -2 is 4
Corner Cases:
Index of element 23 is Unknown

Find out the if linked list contains an element
Linked List contains -2: True
Corner Cases:
Linked List contains 3: False

Insert element in certain index
Insert 41 at index 2: 10-->34-->41-->21-->6-->-2
Corner Cases:
Insert 25 at index 0: 25-->10-->34-->41-->21-->6-->-2
Insert 15 at index 7: 25-->10-->34-->41-->21-->6-->-2-->15
Insert 27 at index -1: Invalid index
25-->10-->34-->41-->21-->6-->-2-->15

Delete node from a certain index
Delete from index 5: 25-->10-->34-->41-->21-->-2-->15
Corner Cases

# Linked List Circle and Dummy/ Non-Dummy

In [ ]:
class DoublyNode:
	def __init__(self, elem, next, prev):
		self.elem = elem
		self.next = next # To store the next node’s reference.
		self.prev = prev # To store the previous node’s reference.

In [ ]:
def createList(a):
  dh = DoublyNode (None, None, None)
  dh.next = dh
  dh.prev = dh
  tail = dh
  for i in range(len(a)):
    n = DoublyNode(a[1], dh, tail)  # (elem, prev, next)
    tail.next = n
    tail = tail.next
    dh.prev = tail
  return dh

In [ ]:
def iteration (dh):
  temp = dh.next
  while temp != dh:
     print(temp.elem)
     temp = temp.next

In [ ]:
# Different way
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None

def iteration(head):
    temp = head
    while temp is not None:
        print(temp.elem)
        temp = temp.next

array = [10, 34, 21, 6, -2]
head = Node(array[0])
for elem in array[1:]:
    node = Node(elem)
    node.next = head
    head = node

iteration(head)

-2
6
21
34
10


In [ ]:
def nodeAt (dh, idx):
  temp = dh.next
  C = 0
  while temp != dh:
    if c == idx:
      return temp
    C += 1
    temp = temp.next
  return None # Invalid Index

In [ ]:
def insertion(dh, elem, idx):
  # Assuming the index is valid
  node_to_insert = DoublyNode(elem, None, None)
  indexed_node = nodeAt(dh, idx) # Retriving the node at the Index
  prev_node = indexed_node.prev # There will always be a previous node
  # Change the connection
  # Observe that no special case is needed
  node_to_insert.next = indexed_node
  node_to_insert.prev = prev_node
  prev_node.next = node_to_insert
  indexed_node.prev = node_to_insert

In [ ]:
  def removal (dh, idx):
    # Assuming the idx is valid
    node_to_remove = nodeAt(dh, idx)
    prev_node = node_to_remove.prev
    next_node = node_to_remove.next
    # Change the connection
    # No special case is needed
    prev_node.next = next_node
    next_node.prev = prev_node
    node_to_remove.next = None
    node_to_remove.prev = None
    return node_to_remove.elem # Returning the removed element

In [ ]:
def B():
  print("B")

def A():
  B()
  print("A")

def main():
  A()
  print("Main")

if __name__ == "__main__":
  main()

B
A
Main


# Extra Task of Lab

In [ ]:
import numpy as np

In [ ]:
class Node:
  def __init__(self, e, n, p):
    self.element = e
    self.next = n
    self.prev = p

In [ ]:
class DoublyList:

  # Creates a Dummy Head for Dummy Headed Circular Doubly Circular Linked List.
  def __init__(self):
    self.head = Node(None, None, None)  # Create the dummy head
    self.head.next = self.head
    self.head.prev = self.head


  #create a DHDCL from an array
  def create_list(self, l):
    for elem in l:
      self.insert(elem, self.countNode())


  # Counts the number of Nodes in the list and return the number
  def countNode(self):
    count = 0
    current = self.head.next
    while current != self.head:
      count += 1
      current = current.next
    return count


  # prints the elements in the list forward
  def forwardprint(self):
    current = self.head.next
    while current != self.head:
      print(current.element, end=' ')
      current = current.next
    print()


  # prints the elements in the list backward
  def backwardprint(self):
    current = self.head.prev
    while current != self.head:
      print(current.element, end=' ')
      current = current.prev
    print()


  # returns the reference of the at the given index. For invalid index return None.
  def nodeAt(self, idx):
    if idx < 0 or idx >= self.countNode():  # Check for invalid index
      return None
    current = self.head.next
    count = 0
    while current != self.head:
      if count == idx:
        return current
      count += 1
      current = current.next
    return None


  # returns the index of the containing the given element. if the element does not exist in the List, return -1.
  def indexOf(self, elem):
    current = self.head.next
    index = 0
    while current != self.head:
      if current.element == elem:
        return index
      current = current.next
      index += 1
    return -1



  # insert at specific index of the DHDCL
  def insert(self, elem, idx):
    current = self.head.next
    index = 0
    while current != self.head:
      if current.element == elem:
        return index
      current = current.next
      index += 1
    return -1


  #removes the node of the specific index and returns the element of the node
  def remove(self, idx):
    if idx < 0 or idx >= self.countNode():  # Check for invalid index
      print("Invalid index for removal.")
      return None
    current = self.nodeAt(idx)
    current.prev.next = current.next
    current.next.prev = current.prev
    return current.element

In [ ]:
print("///  Test 01  ///")
h1 = DoublyList() # Creates a dummy headed doubly circular linked list
h1.create_list(np.array([10,20,30,40]))
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 10,20,30,40.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 40,30,20,10.
print('Total Nodes: ', end = ' ')
print(h1.countNode()) # This should print: 4
print()

print("///  Test 02  ///")
# returns the reference of the at the given index. For invalid idx return None.
print('Node at 2nd index: ', end = ' ')
n = h1.nodeAt(2)
print(n.element if n!=None else 'Index Error')# This should print: 30.
print('Node at 0th index: ', end = ' ')
n = h1.nodeAt(0)
print(n.element if n!=None else 'Index Error')# This should print: 10. IGNORE DUMMY HEAD
print('Node at -1th index: ', end = ' ')
n = h1.nodeAt(-1)
print(n.element if n!=None else 'Index Error')# This should print "index error"
print()

print("///  Test 03  ///")
print('Index of element 40:', end = ' ')
# returns the index of the containing the given element. if the element does not exist in the List, return -1.
index = h1.indexOf(40)
print(index) # This should print: 3. In case of element that
print('Index of element 6:', end = ' ')
index = h1.indexOf(6)
print(index) # doesn't exists in the list this will print -1.
print()

print("///  Test 04  ///")
print('Inserting 85 in 0th index')
h1.insert(85,0)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,30,40.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 40,30,20,10,85.

print()
print('Inserting 95 in 3rd index')
h1.insert(95,3)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,95,30,40.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 40,30,95,20,10,85.

print()
print('Inserting 75 in 6th index')
h1.insert(75,6)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,95,30,40,75.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 75,40,30,95,20,10,85.
print()


print("///  Test 05  ///")
h2 = DoublyList() # uses the constructor
h2.create_list(np.array([10, 20, 30, 40, 50, 60, 70]))
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 10,20,30,40,50,60,70.
print()

print('Removing node from 0th index')
print("Removed element: "+ str(h2.remove(0))) # This should print: Removed element: 10
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,50,60,70.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 70,60,50,40,30,20.
print()

print('Removing node from 3rd index')
print("Removed element: "+ str(h2.remove(3))) # This should print: Removed element: 50
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,60,70.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 70,60,40,30,20.
print()

print('Removing node from 4th index')
print("Removed element: "+ str(h2.remove(4))) # This should print: Removed element: 70
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,60.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 60,40,30,20.
print()

///  Test 01  ///
Forward Print:  
Backward Print:  
Total Nodes:  0

///  Test 02  ///
Node at 2nd index:  Index Error
Node at 0th index:  Index Error
Node at -1th index:  Index Error

///  Test 03  ///
Index of element 40: -1
Index of element 6: -1

///  Test 04  ///
Inserting 85 in 0th index
Forward Print:  
Backward Print:  

Inserting 95 in 3rd index
Forward Print:  
Backward Print:  

Inserting 75 in 6th index
Forward Print:  
Backward Print:  

///  Test 05  ///
Forward Print:  

Removing node from 0th index
Invalid index for removal.
Removed element: None
Forward Print:  
Backward Print:  

Removing node from 3rd index
Invalid index for removal.
Removed element: None
Forward Print:  
Backward Print:  

Removing node from 4th index
Invalid index for removal.
Removed element: None
Forward Print:  
Backward Print:  



In [ ]:
# OUTPUT
import numpy as np
class Node:
  def __init__(self, e, n, p):
    self.element = e
    self.next = n
    self.prev = p

class DoublyList:

  # Creates a Dummy Head for Dummy Headed Circular Doubly Circular Linked List.
  def __init__(self):
    self.head = Node(None, None, None)  # Create the dummy head
    self.head.next = self.head  # Point the next of dummy head to itself to create an empty circular list
    self.head.prev = self.head  # Point the prev of dummy head to itself to create an empty circular list

  # Create a DHDCL from an array
  def create_list(self, l):
    for elem in l:
      self.insert(elem, self.countNode())  # Insert each element at the end of the list

  # Counts the number of Nodes in the list and return the number
  def countNode(self):
    count = 0
    current = self.head.next
    while current != self.head:
      count += 1
      current = current.next
    return count

  # Prints the elements in the list forward
  def forwardprint(self):
    current = self.head.next
    while current != self.head:
      print(current.element, end=' ')
      current = current.next
    print()

  # Prints the elements in the list backward
  def backwardprint(self):
    current = self.head.prev
    while current != self.head:
      print(current.element, end=' ')
      current = current.prev
    print()

  # Returns the reference of the node at the given index. For an invalid index, return None.
  def nodeAt(self, idx):
    if idx < 0 or idx >= self.countNode():  # Check for invalid index
      return None
    current = self.head.next
    count = 0
    while current != self.head:
      if count == idx:
        return current
      count += 1
      current = current.next
    return None

  # Returns the index of the node containing the given element. If the element does not exist in the List, return -1.
  def indexOf(self, elem):
    current = self.head.next
    index = 0
    while current != self.head:
      if current.element == elem:
        return index
      current = current.next
      index += 1
    return -1

  # Insert at a specific index of the DHDCL
  def insert(self, elem, idx):
    if idx < 0 or idx > self.countNode():  # Check for invalid index
      print("Invalid index for insertion.")
      return

    new_node = Node(elem, None, None)

    # If inserting at the end or when the list is empty
    if idx == self.countNode():
      new_node.next = self.head
      new_node.prev = self.head.prev
      self.head.prev.next = new_node
      self.head.prev = new_node
    else:
      current = self.nodeAt(idx)
      new_node.next = current
      new_node.prev = current.prev
      current.prev.next = new_node
      current.prev = new_node

  # Removes the node of the specific index and returns the element of the node
  def remove(self, idx):
    if idx < 0 or idx >= self.countNode():  # Check for invalid index
      print("Invalid index for removal.")
      return None
    current = self.nodeAt(idx)
    current.prev.next = current.next
    current.next.prev = current.prev
    return current.element

print("///  Test 01  ///")
h1 = DoublyList()  # Creates a dummy-headed doubly circular linked list
h1.create_list(np.array([10, 20, 30, 40]))
print('Forward Print: ', end=' ')
h1.forwardprint()  # This should print: 10,20,30,40.
print('Backward Print: ', end=' ')
h1.backwardprint()  # This should print: 40,30,20,10.
print('Total Nodes: ', end=' ')
print(h1.countNode())  # This should print: 4
print()

print("///  Test 02  ///")
# returns the reference of the at the given index. For invalid idx return None.
print('Node at 2nd index: ', end = ' ')
n = h1.nodeAt(2)
print(n.element if n!=None else 'Index Error')# This should print: 30.
print('Node at 0th index: ', end = ' ')
n = h1.nodeAt(0)
print(n.element if n!=None else 'Index Error')# This should print: 10. IGNORE DUMMY HEAD
print('Node at -1th index: ', end = ' ')
n = h1.nodeAt(-1)
print(n.element if n!=None else 'Index Error')# This should print "index error"
print()

print("///  Test 03  ///")
print('Index of element 40:', end = ' ')
# returns the index of the containing the given element. if the element does not exist in the List, return -1.
index = h1.indexOf(40)
print(index) # This should print: 3. In case of element that
print('Index of element 6:', end = ' ')
index = h1.indexOf(6)
print(index) # doesn't exists in the list this will print -1.
print()

print("///  Test 04  ///")
print('Inserting 85 in 0th index')
h1.insert(85,0)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,30,40.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 40,30,20,10,85.

print()
print('Inserting 95 in 3rd index')
h1.insert(95,3)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,95,30,40.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 40,30,95,20,10,85.

print()
print('Inserting 75 in 6th index')
h1.insert(75,6)
print('Forward Print: ', end = ' ')
h1.forwardprint() # This should print: 85,10,20,95,30,40,75.
print('Backward Print: ', end = ' ')
h1.backwardprint() # This should print: 75,40,30,95,20,10,85.
print()


print("///  Test 05  ///")
h2 = DoublyList() # uses the constructor
h2.create_list(np.array([10, 20, 30, 40, 50, 60, 70]))
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 10,20,30,40,50,60,70.
print()

print('Removing node from 0th index')
print("Removed element: "+ str(h2.remove(0))) # This should print: Removed element: 10
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,50,60,70.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 70,60,50,40,30,20.
print()

print('Removing node from 3rd index')
print("Removed element: "+ str(h2.remove(3))) # This should print: Removed element: 50
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,60,70.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 70,60,40,30,20.
print()

print('Removing node from 4th index')
print("Removed element: "+ str(h2.remove(4))) # This should print: Removed element: 70
print('Forward Print: ', end = ' ')
h2.forwardprint() # This should print: 20,30,40,60.
print('Backward Print: ', end = ' ')
h2.backwardprint() # This should print: 60,40,30,20.
print()


///  Test 01  ///
Forward Print:  10 20 30 40 
Backward Print:  40 30 20 10 
Total Nodes:  4

///  Test 02  ///
Node at 2nd index:  30
Node at 0th index:  10
Node at -1th index:  Index Error

///  Test 03  ///
Index of element 40: 3
Index of element 6: -1

///  Test 04  ///
Inserting 85 in 0th index
Forward Print:  85 10 20 30 40 
Backward Print:  40 30 20 10 85 

Inserting 95 in 3rd index
Forward Print:  85 10 20 95 30 40 
Backward Print:  40 30 95 20 10 85 

Inserting 75 in 6th index
Forward Print:  85 10 20 95 30 40 75 
Backward Print:  75 40 30 95 20 10 85 

///  Test 05  ///
Forward Print:  10 20 30 40 50 60 70 

Removing node from 0th index
Removed element: 10
Forward Print:  20 30 40 50 60 70 
Backward Print:  70 60 50 40 30 20 

Removing node from 3rd index
Removed element: 50
Forward Print:  20 30 40 60 70 
Backward Print:  70 60 40 30 20 

Removing node from 4th index
Removed element: 70
Forward Print:  20 30 40 60 
Backward Print:  60 40 30 20 



# Stack Implementation

In [ ]:
class Stack:
  def _init_(self):
    self.top = None

  def push(self,elem):
    if self.top == None: #Stack is empty
      self.top = Node(elem, None)
    else:
      newNode = Node (elem, None)
      newNode.next = self.top
      self.top = newNode

  def pop(self):
    if self.top == None:
      return None #Stack Underflow
    else:
      popped = self.top
      self.top  = self.top.next
      popped.next = None
      return popped.element

  def peek(self):
    if self.top == None:
      return None #Stack Underflow
    else:
      return self.top.element

  def Is_Empty(self):
    if self.top == None:
      return "Stack is Empty"

## Queue Implementation by List

In [ ]:
class Node:
  def __init__(self, elem, next):
    self.elem = elem
    self.next = next

In [ ]:
class Queue:
  def init__(self):
    self.front = None
    self.back = None

  def enqueue(self, elem):
    if self.front == None: # This means first item
      self.front = Node(elem, None)
      self.back = self.front # Initially front and back are same
    else:
      n-Node(elem, None)
      self.back.next = n # Inserting at the last
      self.back = self.back.next # Moving back at the end

  def dequeue(self):
    if self.front == None: # For empty Queue
      print("Queue Underflow Exception")
    else:
      dequeued_item = self.front.elem
      self.front = self.front.next # Moving the front pointer
      return dequeued_item # Returning the dequeued item

  def peek(self):
    if self.front == None: # For empty queue
      print("Queue Underflow Exception")
    else:
      return self.front.elem # Returning the fornt item

## Queue Implementation by Array

In [ ]:
class ArrayQueue:
  def _init_(self):
    self.queue = [None] * 10                # Queue with size 10
    self.front = 0                          # Initializing at index 0
    self.back = 0                          # Initializing at index 0
    self.size = 0                           # no elements

  def enqueue(self, elem):
    if self.size == len(self.queue):
      print("Queue Overflow")
    else:
      self.queue[self.back] = elem
      self.back (self.back + 1) % len(self.queue)
      self.size += 1

  def dequeue(self):
    if self.size == 0:
      print("Queue Underflow")
    else:
      dequeued_item = self.queue[self.front]
      self.queue[self.front] = None
      self.front = (self.front + 1) % len(self.queue)
      self.size = 1
      return dequeued_item

  def peek(self):
    if self.size == 0:
      print("Queue Underflow")
    else:
      return self.queue[self.front]

# LAB EVOLUTION  1

In [ ]:
import numpy as np

In [ ]:
def printArray(givenArray):
  rows, columns = givenArray.shape
  for row in range(rows):
    for column in range(columns):
      print (givenArray[row][column], end = " ")
    print()

In [ ]:
def synthesize_sequence(given_sequence):
  num_rows, num_cols = given_sequence.shape
  new_seq = np.array(given_sequence.shape)

  new_list = []
  for row in given_sequence:
    x = rotateRight(row)
    new_list.append(x)
  new_array = np.array(new_list)
  return new_array

def rotateRight(arr):
  temp = arr[len (arr) - 1]
  for i in range(len(arr) - 1, 0, -1):
    arr[i] = arr[i - 1]
  arr[0] = temp
  return arr

# Driver code
given_sequence = np.array([['A', 'C', 'G', 'G'],['T', 'G', 'A', 'A'], ['G', 'G', 'A', 'C'], ['C', 'T', 'G', 'A']])
print("Original Array")
printArray(given_sequence)
print("=====================")
synthesizedArray1 = synthesize_sequence(given_sequence)
print("After Synthesizing")
printArray(synthesizedArray1)
print("=====================")

given_sequence = np.array([['A', 'C', 'G', 'G'], ['T', 'G', 'A', 'A'], ['A', 'G', 'A', 'C'],['A', 'T', 'G', 'A']])
print("Original Array")
printArray(given_sequence)
print("=====================")
synthesizedArray2 = synthesize_sequence(given_sequence)
print("After Synthesizing")
printArray(synthesizedArray2)
print("=====================")

Original Array
A C G G 
T G A A 
G G A C 
C T G A 
After Synthesizing
G A C G 
A T G A 
C G G A 
A C T G 
Original Array
A C G G 
T G A A 
A G A C 
A T G A 
After Synthesizing
G A C G 
A T G A 
C A G A 
A A T G 


# Lab Evaluation On Linked list

In [ ]:
import numpy as np
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

def countNodes(head):
  count = 0
  temp = head
  while temp != None:
    count += 1
    temp = temp.next
  return count

def nodeAt(head, idx):
  temp = head
  for i in range(idx):
    temp = temp.next
    if temp == None:
      break
  return temp

In [ ]:
def removeAllOdd(head):
  temp = head
  size = countNodes(head)
  arr_size = size // 2
  Array = [None] * arr_size
  i = 0
  while temp != None:
    if temp.elem % 2 == 0:
      Array[i] = temp.elem
      temp = temp.next
      i += 1
    else:
      temp = temp.next
      pass

  New_list = createList(Array)
  return New_list

In [ ]:
#Tester Code
head = createList(np.array([5,7,6,21,3,62,213,6,121]))
print("Original Input Linked List:")
printLinkedList(head)
#This should print  5-->7-->6-->21-->3-->62-->213-->6-->121

h=removeAllOdd(head)
print("Output Linked List:")
printLinkedList(h)
#This should print  6-->62-->6

Original Input Linked List:
5-->7-->6-->21-->3-->62-->213-->6-->121

Output Linked List:
6-->62-->6-->None



# Quiz 2

In [ ]:
# Set A Question 1:
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

In [ ]:
class DoublyNode:
	def __init__(self, elem, next, prev):
		self.elem = elem
		self.next = next
		self.prev = prev

In [ ]:
def convert ( dh ):
  if dh.next is None:  # Check if the doubly circular list is empty
    return None

  head = Node(dh.next.elem, None)
  current = head  # Track the current node in the singly linear list

  node = dh.next.next  # Start from the second node in the doubly circular list
  while node != dh.next:
    current.next = Node(node.elem, None)  # Create a new node and set it as the next node
    current = current.next  # Move to the next node in the singly linear list
    node = node.next  # Move to the next node in the doubly circular list

  return head

In [ ]:
# GPT-4
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

class DoublyCircularLinkedList:
  def __init__(self):
    self.head = None

  def append(self, data):
    new_node = Node(data)

    if not self.head:
      self.head = new_node
      new_node.next = new_node
    else:
      temp = self.head
      while temp.next != self.head:
          temp = temp.next

      new_node.next = self.head
      temp.next = new_node

  def convert_to_singly_linear(self):
      if not self.head:
        return None

      current = self.head
      singly_list = Node(current.data)
      temp = singly_list

      current = current.next
      while current != self.head:
        new_node = Node(current.data)
        temp.next = new_node
        temp = new_node
        current = current.next
      return singly_list

# Create a dummy-headed doubly circular linked list
doubly_linked_list = DoublyCircularLinkedList()
doubly_linked_list.append(1)
doubly_linked_list.append(2)
doubly_linked_list.append(3)
doubly_linked_list.append(4)

# Convert to a singly linear linked list
singly_linked_list = doubly_linked_list.convert_to_singly_linear()

# Print the singly linear linked list
temp = singly_linked_list
while temp:
    print(temp.data, end=" ")
    temp = temp.next

# Output: 1 2 3 4


1 2 3 4 

In [ ]:
# Set B Question 1:
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

class DoublyNode:
  def __init__(self, elem, next, prev):
    self.elem = elem
    self.next = next
    self.prev = prev

def convert(dh):
  if dh is None:
    return None
  dummy = DoublyNode(None, None, None)
  dummy.next = dummy
  dummy.prev = dummy

  current = dh
  prev_doubly = dummy

  while current is not None:
    doubly_node = DoublyNode(current.elem, None, prev_doubly)
    prev_doubly.next = doubly_node
    doubly_node.prev = prev_doubly
    prev_doubly = doubly_node
    current = current.next
  prev_doubly.next = dummy
  dummy.prev = prev_doubly
  return dummy

# SPRING 2023 MID Question

In [ ]:
# Question 1
def multiple_repeat(a):
  repeat_counts = {}
  for i in a:
    if i not in repeat_counts:
      repeat_counts[i] = 1
    elif i in repeat_counts:
      repeat_counts[i] += 1

  flag = False
  values_list = list(repeat_counts.values())
  values_list.remove(1)                      # This will remove all the unrepeted value
  for i in range(len(values_list)):
    if values_list[i] in values_list[i+1:]:
      flag = True
  return flag

array = [4,5,6,6,4,3,6,4]
print(multiple_repeat(array))

array = [3,4,6,3,4,7,4,6,8,6,6]
print(multiple_repeat(array))

True
False


In [ ]:
# Question 2
#Run this cell
class Node:
  def __init__(self,elem,next = None):
    self.elem = elem
    self.next = next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

def remove_compartment(head,n):
  size = count(head)
  idx = size - n
  result = remove(head, idx)
  return result

def nodeAt (head, idx):
  count = 0
  temp = head
  obj = None
  while temp != None:
    if count == idx:
      obj = temp
      break
    temp = temp.next
    count += 1
  return obj

def count (head):
  count = 0
  temp = head
  while temp != None:
    count += 1
    temp = temp.next
  return count

def remove (head, idx):
  if idx == 0:
    head = head.next
  elif idx >= 1 and idx < count (head):
    n1 = nodeAt(head, idx - 1)
    removed_node = n1.next
    n1.next= removed_node.next
  return head

head = createList(np.array([10,20,5,15,25]))
print('Original Compartment Sequence: ', end = ' ')
printLinkedList(head)
head = remove_compartment(head,2)
print('Changed Compartment Sequence: ', end = ' ')
printLinkedList(head)
print()
head = createList(np.array([10,20,5,15,25]))
print('Original Compartment Sequence: ', end = ' ')
printLinkedList(head)
head = remove_compartment(head,8)
print('Changed Compartment Sequence: ', end = ' ')
printLinkedList(head)
print()

Original Compartment Sequence:  10-->20-->5-->15-->25

Changed Compartment Sequence:  10-->20-->5-->25


Original Compartment Sequence:  10-->20-->5-->15-->25

Changed Compartment Sequence:  10-->20-->5-->15-->25




In [ ]:
# Question 3
class Stack:
  def __init__(self):
    self.__top = None

def diamond_count(stack,string):
  open = Stack()
  close = Stack()

  open_counter = 0
  close_counter = 0

  for i in string:
    if i == "<":
      open_counter += 1
    if i == ">":
      close_counter += 1

  if open_counter == close_counter:
    count_diamond = open_counter
  elif open_counter > close_counter:
    count_diamond = close_counter
  elif open_counter < close_counter:
    count_diamond = open_counter

  return count_diamond

print('Test 01')
stack = Stack()
string = '<..><.<..>> '
returned_value = diamond_count(stack,string)
print(f'Number of Diamonds: {returned_value}')

print('Test 02')
stack = Stack()
string = '<<<..<......<<<<....>'
returned_value = diamond_count(stack,string)
print(f'Number of Diamonds: {returned_value}')

Test 01
Number of Diamonds: 3
Test 02
Number of Diamonds: 1


# LAb Mid Sec 17

In [ ]:
import numpy as np
class Node:
  def __init__(self,e,n):
    self.elem = e
    self.next = n

In [ ]:
def createList(arr):
  head = Node(arr[0],None)
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i],None)
    tail.next = newNode
    tail = newNode
  return head

In [ ]:
# def remove_dup(head):
#   new_list = []
#   temp = head
#   while temp != None:
#     if temp.elem == temp.next.elem:
#       if temp.elem not in new_list:
#         new_list.append(temp.elem)
#   new_array = np.array(new_list)
#   result = createList(new_array)
#   return result
def remove_dup(head):
  curr = head
  while curr != None:
    next_node = curr.next
    while next_node != None and next_node.elem == curr.elem:
      next_node = next_node.next
    curr.next = next_node
    curr = next_node
  return head

In [ ]:
def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

In [ ]:
#Tester Code
head=createList(np.array([2,2,2,2,7,7,9,10,10,10,10,12]))
printLinkedList(head) #This should print    2-->2-->2-->2-->7-->7-->9-->10-->10-->10-->10-->12
h=remove_dup(head)
printLinkedList(h)    #This should print    2-->7-->9-->10-->12

2-->2-->2-->2-->7-->7-->9-->10-->10-->10-->10-->12

2-->7-->9-->10-->12



# Mid Set-A

In [ ]:
# Question 1 (ii)
import numpy as np
def raw_min_max(arr):
  row_max = []
  for row in arr:
    max_value = row[0]
    for i in range(1,len(row)):
      if row[i] > max_value:
        max_value = row[i]
    row_max.append(max_value)
  min_value = row_max[0]
  for i in range(1,len(row_max)):
    if row_max[i] > min_value:
      min_value = row_max[i]
  return min_value

arr = np.array([[2,7,5],[9,3,8],[1,4,6]])
print(f'Maximum value :{raw_min_max(arr)}')

Maximum value :9


In [ ]:
# Question 2 (ii)
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1, len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def is_sorted_des(head):
  if head == None or head.next == None:
    return True

  temp = head
  while temp.next != None:
    if temp.elem > temp.next.elem:
      return False
    temp = temp.next
  return True


arr1 = [10,20,5,15,25]
arr2 = [5,15,20,30,40]
a = createList(arr1)
b = createList(arr2)
print(f'Test 1: {is_sorted_des(a)}')  # Output: Test 1: False
print(f'Test 2: {is_sorted_des(b)}')  # Output: Test 2: True

Test 1: False
Test 2: True


In [ ]:
# Question 3 (ii)
class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.__top = None

  def push(self,elem):
    if self.__top == None: #Stack is empty
      self.__top = Node(elem, self.__top)
    else:
      newNode = Node (elem, self.__top)
      newNode.next = self.__top
      self.__top = newNode

  def pop(self):
    if self.__top == None:
      return None #Stack Underflow
    else:
      popped = self.__top
      self.__top  = self.__top.next
      popped.next = None
      return popped.elem

  def peek(self):
    if self.__top == None:
      return None #Stack Underflow
    else:
      return self.__top.elem

  def isEmpty(self):
    if self.__top == None:
      return True

def remove_middle(stack):
  stack_size = 0
  temp_stack = Stack()

  while not stack.isEmpty():
    temp_stack.push(stack.pop())
    stack_size += 1
  middle_index = stack_size // 2
  for i in range(stack_size):
    if i != middle_index:
      stack.push(temp_stack.pop())
    else:
      temp_stack.pop()
  while not temp_stack.isEmpty():
    stack.push(temp_stack.pop())


def print_stack(st):
  if st.isEmpty():
    return
  p = st.pop()
  print('|',p,end=' ')
  if p<10:
    print(' |')
  else:
    print('|')
  print('------')
  print_stack(st)
  st.push(p)

st = Stack()
st.push(25)
st.push(15)
st.push(5)
st.push(20)
st.push(10)
print_stack(st)
print('------')
remove_middle(st)
print_stack(st)
print()
st1 = Stack()
st1.push(35)
st1.push(25)
st1.push(15)
st1.push(5)
st1.push(20)
st1.push(10)
print_stack(st1)
print('------')
remove_middle(st1)
print_stack(st1)

| 10 |
------
| 20 |
------
| 5  |
------
| 15 |
------
| 25 |
------
------
| 10 |
------
| 20 |
------
| 15 |
------
| 25 |
------

| 10 |
------
| 20 |
------
| 5  |
------
| 15 |
------
| 25 |
------
| 35 |
------
------
| 10 |
------
| 20 |
------
| 15 |
------
| 25 |
------
| 35 |
------


In [ ]:
def remove_middle(stack):
    # Find the size of the stack
    stack_size = 0
    temp_stack = Stack()

    while not stack.isEmpty():
        temp_stack.push(stack.pop())
        stack_size += 1

    # Calculate the middle index
    middle_index = stack_size // 2

    # Remove the middle element
    for i in range(stack_size):
        if i != middle_index:
            stack.push(temp_stack.pop())
        else:
            temp_stack.pop()

    # Revert the original stack
    while not temp_stack.isEmpty():
        stack.push(temp_stack.pop())

# Rest of your code remains unchanged
st = Stack()
st.push(25)
st.push(15)
st.push(5)
st.push(20)
st.push(10)
print_stack(st)
print('------')
remove_middle(st)
print_stack(st)


| 10 |
------
| 20 |
------
| 5  |
------
| 15 |
------
| 25 |
------
------
| 10 |
------
| 20 |
------
| 15 |
------
| 25 |
------


# Mid Set-B

In [ ]:
# Question 1 (ii)
import numpy as np
def raw_min_max(arr):
  row_min = []
  for row in arr:
    min_value = row[0]
    for i in range(1,len(row)):
      if row[i] < min_value:
        min_value = row[i]
    row_min.append(min_value)
  max_value = row_min[0]
  for i in range(1,len(row_min)):
    if row_min[i] > max_value:
      max_value = row_min[i]
  return max_value

arr = np.array([[2,7,5],[9,3,8],[1,4,6]])
print(f'Minimum value :{raw_min_max(arr)}')

Minimum value :3


In [ ]:
# Question 2 (ii)
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1, len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def is_sorted_des(head):
  if head == None or head.next == None:
    return True

  temp = head
  while temp.next != None:
    if temp.elem < temp.next.elem:
      return False
    temp = temp.next
  return True


arr1 = [10,20,5,15,25]
arr2 = [40,30,20,15,5]
a = createList(arr1)
b = createList(arr2)
print(f'Test 1: {is_sorted_des(a)}')  # Output: Test 1: False
print(f'Test 2: {is_sorted_des(b)}')  # Output: Test 2: True

Test 1: False
Test 2: True


In [ ]:
# Question 3 (ii)
class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.__top = None

  def push(self,elem):
    if self.__top == None: #Stack is empty
      self.__top = Node(elem, self.__top)
    else:
      newNode = Node (elem, self.__top)
      newNode.next = self.__top
      self.__top = newNode

  def pop(self):
    if self.__top == None:
      return None #Stack Underflow
    else:
      popped = self.__top
      self.__top  = self.__top.next
      popped.next = None
      return popped.elem

  def peek(self):
    if self.__top == None:
      return None #Stack Underflow
    else:
      return self.__top.elem

  def isEmpty(self):
    if self.__top == None:
      return True

def remove_middle(stack):
  stack_size = 0
  temp_stack = Stack()

  while not stack.isEmpty():
    temp_stack.push(stack.pop())
    stack_size += 1
  middle_index = stack_size // 2
  for i in range(stack_size):
    if i != middle_index:
      stack.push(temp_stack.pop())
    else:
      temp_stack.pop()
  while not temp_stack.isEmpty():
    stack.push(temp_stack.pop())


def print_stack(st):
  if st.isEmpty():
    return
  p = st.pop()
  print('|',p,end=' ')
  if p<10:
    print(' |')
  else:
    print('|')
  print('------')
  print_stack(st)
  st.push(p)

st = Stack()
st.push(25)
st.push(15)
st.push(5)
st.push(20)
st.push(10)
print_stack(st)
print('------')
remove_middle(st)
print_stack(st)
print()
st1 = Stack()
st1.push(35)
st1.push(25)
st1.push(15)
st1.push(5)
st1.push(20)
st1.push(10)
print_stack(st1)
print('------')
remove_middle(st1)
print_stack(st1)

| 10 |
------
| 20 |
------
| 5  |
------
| 15 |
------
| 25 |
------
------
| 10 |
------
| 20 |
------
| 15 |
------
| 25 |
------

| 10 |
------
| 20 |
------
| 5  |
------
| 15 |
------
| 25 |
------
| 35 |
------
------
| 10 |
------
| 20 |
------
| 15 |
------
| 25 |
------
| 35 |
------


# After **MID**

# Recursion

In [ ]:
def recursion(n):
  print(n)
  if n == 0:      # Base case
    return
  recursion(n - 1)  # Recursive function call

recursion(4)

4
3
2
1
0


In [ ]:
def factorial(n):
  if n == 0:         # Base case
    return 1
  else:
    return n * factorial(n - 1)   # Recursive function call

factorial(4)

24

In [ ]:
def iterate_count(n):
  if n == 0:      # Base case
    print(n)
    return
  iterate_count(n - 1)   # Recursive function call
  print(n)
  # here is a return in-built works no need to command.

iterate_count(4)

0
1
2
3
4


In [ ]:
# Fibonacci Number of the index
def fibonacci(n):
  if n == 0:      # Base case
    return 0
  elif n == 1:    # Base case
    return 1
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)    # Recursive function call

fibonacci(4)

3

In [ ]:
def fib(n):
  if n < 2 :
    return n       #Base Case
  else:
    return fib(n -1) + fib(n - 2)    # Recursive function call
fib(16)

987

In [ ]:
# Recursive Programming
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

def createList(arr):
  head = Node(arr[0],None)
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i],None)
    tail.next = newNode
    tail = newNode
  return head

# Sum of numbers by iterate
def iterativeSum(head):
  sum = 0
  temp = head
  while temp != None:
    sum += temp.elem
    temp = temp.next
  return sum

head = createList(np.array([10,20,5,15,25]))
print(f'Iterative Sum: {iterativeSum(head)}')

# Recursive Programming ( Sum of numbers )
def recursiveSum(head):
  if head.next == None:
    return head.elem # Base case
  else:
    return head.elem + recursiveSum(head.next)  # Recursive function call

head = createList(np.array([10,20,5,15,25]))
print(f'Recursive Sum :{recursiveSum(head)}')

#Recursive Programming ( Length of String )
def strLength(str):
  if len(str) == 0:
    return 0  # Base case
  else:
    return 1 + strLength(str[1::]) # Recursive function call
              # string starts from 2nd index = 1.
string = "MahinNoor"
print(f'Length of the string  :{strLength(string)}')

# Recursive Programming ( Length of Linked List )
def listLength(head):
  if head == None:
    return 0   # Base case
  else:
    return 1 + listLength(head.next)    # Recursive function call
              # here head.next means rest of the list
head = createList(np.array([10,20,5,15,25]))
print(f'Length of the list :{listLength(head)}')

# Recursive Programming ( Sequential Search in List )
def contains(head,key):
  if head == None:   # Base case
    return False
  elif head.elem == key :   # Base case
    return True
  else:
    return contains(head.next,key)    # Recursive function call

head = createList(np.array([10,20,5,15,25]))
print(f'The list contain the item :{contains(head,5)}')
print(f'The list contain the item :{contains(head,6)}')

# Recursive Programming ( Sequential Search in array )
def contains(arr,key):
  if len(arr) == 0:  # Base case
    return False
  elif arr[0] == key:  # Base case
    return True
  else:
    return contains(arr[1::],key)   # Recursive function call

arr = np.array([10,20,5,15,25])
print(f'The list contain the item :{contains(arr,4)}')
print(f'The list contain the item :{contains(arr,5)}')

# Recursive Programming (Seq Search : Left Index)
def contains(arr,index,key):
  if index >= len(arr):  # Base case
    return False
  elif arr[index] == key:  # Base case
    return True
  else:
    return  contains(arr,index + 1,key)   # Recursive function call

arr = np.array([10,20,5,15,25])
print(f'The list contain the item :{contains(arr,0,4)}')
print(f'The list contain the item :{contains(arr,0,5)}')

# Recursive Programming ( Find Maximum in Linear List )
def maximum(a,b):
  if a >= b:
    return a
  else:
    return b

def findMax(head):
  if head.next == None:
    return head.elem  # Base ase
  else:
    maxRest = findMax(head.next)   # Recursive function call
    return maximum(head.elem,maxRest)

head = createList(np.array([10,20,5,15,25]))
print(f'Maximum of the list: {findMax(head)}')

# Recursive Programming (Find Maximum in Linear Array)
def maximum(a,b):
  if a >= b:
    return a
  else:
    return b

def findMax(arr,index):
  if index == len(arr) - 1:
    return arr[index]  # Base ase
  else:
    maxRest = findMax(arr , index + 1)   # Recursive function call
    return maximum(arr[index] , maxRest)

arr = np.array([10,20,5,15,40])
print(f'Maximum of the list: {findMax(arr,0)}')

# Recursive Programming ( Exponentiation )
def exp(a,n):
  if n == 0:
    return 1
  else:
    return a * exp(a , n - 1)

print(f'Exponentiation: {exp(2,3)}')

Iterative Sum: 75
Recursive Sum :75
Length of the string  :9
Length of the list :5
The list contain the item :True
The list contain the item :False
The list contain the item :False
The list contain the item :True
The list contain the item :False
The list contain the item :True
Maximum of the list: 25
Maximum of the list: 40
Exponentiation: 8


# Recursion (Advanced)

In [ ]:
# Recursive Programming (Binary Search):
def contains(arr, left_index, right_index, key):
  if left_index > right_index:     # Base case
    return False
  else:
    mid_index = (left_index + right_index) // 2
    if key == arr[mid_index]:      # Base case
      return True
    elif key > arr[mid_index]:
      return contains(arr, mid_index + 1, right_index, key)  # Recursive function call
    else:
      return contains(arr, left_index, mid_index - 1, key)   # Recursive function call

arr = np.array([10,20,5,15,25])
print(f'The list contain the item :{contains(arr,0,len(arr)-1,4)}')
print(f'The list contain the item :{contains(arr,0,len(arr)-1,5)}')

The list contain the item :False
The list contain the item :True


In [ ]:
# Recursive Programming (Find Maximum - Binary)
def maximum(a,b):
  if a >= b:
    return a
  else:
    return b

def findMax(arr, left_index, right_index):
  if left_index == right_index:    # Base case
    return arr[left_index]
  else:
    mid_index =  (left_index + right_index) // 2
    max_of_left_half = findMax(arr, left_index, mid_index)  # Recursive function call
    max_of_right_half = findMax(arr, mid_index + 1, right_index)  # Recursive function call
    return maximum(max_of_left_half, max_of_right_half)

arr = np.array([10,20,5,15,40])
print(f'Maximum of the list: {findMax(arr, 0, len(arr) - 1)}')

Maximum of the list: 40


In [ ]:
# Recursive Programming (Exponentiation Efficient)
def exp(a,n):
  if n == 0:
    return 1          # Base case
  elif n % 2 == 0:
    temp = exp(a, n/2)
    return temp * temp
  else:
    temp = exp(a, (n -1)/2)
    return temp * temp * a

print(f'Exponentiation: {exp(2,3)}')

Exponentiation: 8


# Quiz 3 Set A

In [ ]:
# Question 1
def find_vowel(str,idx):
  vowel = "aeiouAEIOU"
  if str[idx] in vowel:
    return str[idx]
  else:
    return find_vowel(str,idx + 1)

string = "Mahin"
print(find_vowel(string,0))

a


In [ ]:
# Question 2 ✅
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

def printRev(head):
  if head is None:
    return
  printRev(head.next)
  if head.elem < 0 and head.elem % 2 != 0:
    print(head.elem, end=" ")

# Sample Input: -11 -> (-20) -> 31-> -41-> 51 -> None
head = Node(-11, Node(-20, Node(31, Node(-41, Node(51, None)))))

printRev(head)  # Output: -41 -11

-41 -11 

# Quiz 3 Set B

In [ ]:
# Question 1
def find_cons(str,idx):
  consonant = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"
  if str[idx] in consonant:
    return str[idx]
  else:
    return find_vowel(str,idx + 1)

string = "Mahin"
print(find_cons(string,0))

M


In [ ]:
# Question 2 ✅
class Node:
  def __init__(self, e, n):
    self.elem = e
    self.next = n

def printRev(head):
  if head is None:
    return
  printRev(head.next)
  if head.elem > 0 and head.elem % 2 == 0:
    print(head.elem, end=" ")

# Sample Input: 10 -> (-20) -> 31-> 40-> 50 -> None
head = Node(10, Node(-20, Node(31, Node(40, Node(50, None)))))

printRev(head)  # Output: 50 40 1

50 40 10 

# Hashing

In [ ]:
class HashTable:
  def __init__(self): #Creates a hashtable
    self.MAX = 10
    self.arr = [None for i in range(self.MAX)]

  def get_hash(self, key): #Maps the hash values
    hash = 0
    for char in key:
        hash += ord(char)
    return hash % self.MAX

  def __getitem__(self, index): #Getting the values after hash mapping
    h = self.get_hash(index)
    return self.arr[h]

  def __setitem__(self, key, val): #Creates the hash value for the indices
    h = self.get_hash(key)
    self.arr[h] = val

  def __delitem__(self, key): #Deletes a value after hash mapping
    h = self.get_hash(key)
    self.arr[h] = None

In [ ]:
class Node:
  def __init__(self, elem, key=None, next=None):
  self.elem=elem
  self.next=next
  self.key=key

class HashTableWithChaining:
  def __init__(self):
    self.MAX = 10
    self.arr = [None for i in range(self.MAX)]

  def get_hash(self, key):
    hash = 0
    for char in key:
        hash += ord(char)
    return hash % self.MAX

  def __getitem__(self, key):
    hash = self.get_hash(key)
    head= self.arr[hash]
    while head!=None:
      if (head.key==key):
        return head.elem
      head=head.next
    return "Not Found"

  def __setitem__(self, key, val):
    h = self.get_hash(key)
    print(h, key)
    if (self.arr[h]==None):
      self.arr[h] = Node(val, key)
    else:
      x= Node(val, key)
      x.next= self.arr[h]
      self.arr[h] =x
    # print(key, val, h, self.arr[h].elem)

  def __delitem__(self, key):
    h = self.get_hash(key)
    parent=None
    child=None
    n=self.arr[h]
    if (n.next==None):
      n=None
    else:
      while(n.next!=None):
        if n.next.key==key:
          parent=n
          child=n.next.next
          parent.next.val=None
          parent.next.next=None
          parent.next.key=None
          parent.next=child
          break
        n=n.next

    print(f"{key} deleted!")

In [ ]:
class Node:
  def __init__(self, elem, key=None, next=None):
    self.elem=elem
    self.next=next
    self.key=key

class HashTableLinearProbing:
  def __init__(self): #Creates a hashtable
    self.MAX = 10
    self.arr = [None for i in range(self.MAX)]

  def get_hash(self, key): #Maps the hash values
      hash = 0
      for char in key:
          hash += ord(char)
      return hash % self.MAX

  def __getitem__(self, key): #Getting the values after hash mapping
    h = self.get_hash(key)
    for i in range(0,self.MAX):
      if self.arr[(h+i)%self.MAX]!=None:
        if self.arr[(h+i)%self.MAX].key == key:
          return self.arr[(h+i)%self.MAX].elem
    return f"Not found"

  def __setitem__(self, key, val): #Creates the hash value for the indices
    h = self.get_hash(key)
    for i in range(0,self.MAX):
      if (self.arr[(h+i)%self.MAX])==None:
        self.arr[(h+i)%self.MAX]=Node(val,key)
        print(h, self.arr[(h+i)%self.MAX].key)
        break

  def __delitem__(self, key): #Deletes a value after hash mapping
    h = self.get_hash(key)
    for i in range(0,self.MAX):
      if self.arr[(h+i)%self.MAX]!=None:
        if self.arr[(h+i)%self.MAX].key == key:
          self.arr[(h+i)%self.MAX]= None
    print(f"{key} deleted!")

In [ ]:
# Forward Chaining (Insert)
def Forward_Chaining_Insert(arr):
  hash_table = [None] * len(arr)

  for element in arr:
    hash_value = hash_func(elem)
    if(hash_table [hash_value] == None):
      hash_table [hash_value] = Node(elem, None)
    else:
      current = hash_table [hash_value]
      hash_table[hash_value] = Node(elem, current)

# Forward Chaining (Search)
def Forward_Chaning_search(elem):
  hash_value = hash_func(elem)
  temp = hash_table[hash_value]

  while temp != None:
    if temp.elem == elem:
      return True
    temp = temp.next
  return False

# Tree

In [ ]:
class Node:   # Tree class for any kind of tree
  def __init__(self,elem):
    self.elem = elem
    self.children = []

In [ ]:
# Making of a tree
root = Node(1)
root.children += [Node(2)]
root.children += [Node(3)]
root.children += [Node(4)]
root.children[0].children += [Node(5)]
root.children[0].children += [Node(6)]
root.children[1].children += [Node(7)]

In [ ]:
class BTNode:  # Binary Tree's Class
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

In [ ]:
# Build Tree From Array
def tree_construction(arr,i,n): # here i = array index 1, n = array size / len(arr)
  if i < n:
    if arr[i] != None:
      root = Node(arr[i])
      root.left = tree_construction(arr, 2 * i, n)
      root.right = tree_construction(arr, 2 * i + 1, n)
  return root

In [ ]:
def pre_order(root): # Root -> Left -> Right
  if root != None:
    print(root.elem, end = " ")
    pre_order(root.left)
    pre_order(root.right)

In [ ]:
def inorder(root): # Left -> Root -> Right **** This will create acceding order arr
  if root != None:
    return
  inorder(root.left)
  print(root.elem, end = ' ')
  inorder(root.right)

In [ ]:
def post_order(root): # Left -> Right -> Root
  if root != None:
    post_order(root.left)
    post_order(root.right)
    print(root.elem, end = " ")

In [ ]:
# Build Array From Tree
array = [None] * 16 # depends on number of root.

def array_construction(n,i): # n = node root
  if n == None:
    return None
  else:
    array[i] = n.elem
    array_construction(n.left, 2 * i)
    array_construction(n.right, 2 * i + 1)

In [ ]:
# Count Nodes of Tree
def count(root):
  if root == None:
    return 0
  else:
    return 1 + count(root.left) + count(root.right)

In [ ]:
# Find Level of a Node in tree
def get_level(node, elem):
  node_level = 0
  if node == None:
    return 0

  if node.elem == elem:
    return node_level

  downlevel = get_level(node.left, node_level + 1, elem)
  if downlevel != 0:
    return downlevel
  downlevel = get_level(node.right, node_level + 1, elem)
  return downlevel

In [ ]:
# Find height of a Node in tree
def max(a,b):
  if a > b:
    return a
  else:
    return b

def height(node):
  if node is None:
      return -1
  else:
    return 1 + max(height(node.left), height(node.right))

In [ ]:
# Insert Node in Binary Search Tree
def addNode(root,i):
  if i < root.elem and root.left == None:
    n = Node(i)
    root.left = n
  elif i > root.elem and root.right == None:
    n = Node(i)
    root.right = n
  if i < root.elem and root.left != None:
    addNode(root.left, i)
  elif i > root.elem and root.right != None:
    addNode(root.right, i)
  return root

In [ ]:
# Find the minimum value in BST
def min_ValueNode(node):
    current = node
    while current.left:
        current = current.left
    return current

In [ ]:
# Find the maximum value in BST
def max_value(node):
    current = node
    while current.right:
        current = current.right
    return current

In [ ]:
# Binary Search Tree - Delete Node
def deleteNode (root, key):
  if root is None:
    return root

  if key < root.elem:
    root.left = deleteNode (root.left, key)
  elif (key> root.elem):
    root.right = deleteNode(root.right, key)
  else:
    if root.left == None:
      temp = root.right
      root = None
      return temp
    elif root.right == None:
      temp = root.left
      root = None
      return temp
    temp = min_ValueNode(root.right)
    root.key = temp.elem
    root.right = deleteNode(root.right, temp.elem)
  return root

In [ ]:
def pushTreeNodes(root, list):
  if root == None:
    return
  pushTreeNodes(root.left, list)
  list.append(root)
  pushTreeNodes(root.right, list)

In [ ]:
def builtBalancedBST(arr, st, end):
  if st > end:
    return None
  mid = (st + end) // 2
  root = arr[mid]
  root.left =  builtBalancedBST(arr, st, (mid - 1))
  root.righr =  builtBalancedBST(arr, (mid + 1), end)
  return root

In [ ]:
# Check if Two Binary Trees are Identical
def identicalTrees(a, b):
  if a is None and b is None:
    return True
  if a is not None and b is not None:
    return (a.elem == b.elem) and identicalTrees(a.left, b.left) and identicalTrees(a.right, b.right)
  return False

In [ ]:
# Check if a Binary Tree is Balanced
def isBalanced(root):
  if root is None:
    return True
  lst = height(root.left)
  rst = height(root.right)
  if (abs(st - rst) <= 1) and isBalanced(root.left) is True and isBalanced(root.right) is True:
    return True
  return False

In [ ]:
# Cheak duplicates
def cheakDup(root):
  s = set()
  return cheakDupUtil(root, s)

def cheakDupUtil(root, s):
  if root == None:
    return False
  # don't understand why do we need it.